version: '3'

services:
  payload-example:
    build:
      context: ./src/payload-example
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - postgres-payload-example
    env_file:
      - payload-example.env

  postgres-payload-example:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: payload
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  
  payload-example-ecommerce:
    build:
      context: ./src/payload-example-ecommerce
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
    depends_on:
      - postgres-payload-example-ecommerce
    env_file:
      - payload-example-ecommerce.env
  postgres-payload-example-ecommerce:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: payload
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"


volumes:
  pgdata: